/*
 Navicat Premium Data Transfer

 Source Server         : mysql
 Source Server Type    : MySQL
 Source Server Version : 50733
 Source Host           : localhost:3306
 Source Schema         : hyht

 Target Server Type    : MySQL
 Target Server Version : 50733
 File Encoding         : 65001

 Date: 01/08/2022 11:26:25
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for t_fp_fbxx
-- ----------------------------
DROP TABLE IF EXISTS `t_fp_fbxx`;
CREATE TABLE `t_fp_fbxx`  (
  `fpdjh` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '发票登记号',
  `type_of_invoice` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '发票类型（通用机打发票，通用机打电子发票）',
  `code_of_invoice` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '发票代码',
  `number_of_invoice` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '发票号码',
  `billing_month` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '开票月份',
  `total` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '合计（取自发票表hj）',
  `remarks` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '备注（取自发票表）',
  `payee` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '收款人（tyyl,slmz）',
  `industry_classification` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '行业分类',
  `Industry_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '行业名称',
  `application_number` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '申请表号码（hyhl_02/62/72/82/85/89/91税务机关代开）_fp',
  `tax_payment_voucher_number` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '完税凭证号码（fyhl_02/62/72/82/85/87/89/91税务机关代开)_fp',
  `network_invoicing_number` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '网络开票流水号',
  `drawee_tin` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '受票方纳税人识别号',
  `drawee_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '受票方纳税人名称',
  `drawee_phone` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '受票方地址及电话',
  `drawee_bank_account` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '受票方银行及账户',
  `seller_tin` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '销方纳税人识别号',
  `seller_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '销方纳税人名称',
  `seller_phone` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '销方地址及电话',
  `seller_bank_account` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '销方银行及账户',
  `issuer` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '开票人',
  `amount` decimal(20, 2) NULL DEFAULT NULL COMMENT '金额',
  `tax_rate` decimal(20, 2) NULL DEFAULT NULL COMMENT '税率',
  `tax_amount` decimal(20, 2) NULL DEFAULT NULL COMMENT '税额',
  `warehouse_no` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '仓号（hyfl_07粮食收购）',
  `pi_jia_number` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '批价单号（hyfl_07粮食收购）',
  `code_number` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '划码单号（hyfl_07粮食收购）',
  `moisture_content` decimal(20, 2) NULL DEFAULT NULL COMMENT '水份（hyfl_07粮食收购）',
  `impurities` decimal(20, 2) NULL DEFAULT NULL COMMENT '杂质（hyfl_07粮食收购）',
  `rough` decimal(20, 2) NULL DEFAULT NULL COMMENT '粗糙（hyfl_07粮食收购）',
  `each_other_mix` decimal(20, 2) NULL DEFAULT NULL COMMENT '互混（hyfl_07粮食收购）',
  `bulk_density` decimal(20, 2) NULL DEFAULT NULL COMMENT '容重（hyfl_07粮食收购）',
  `imperfect_grain` decimal(20, 2) NULL DEFAULT NULL COMMENT '不完善粒（hyfl_07粮食收购）',
  `pure_grain_rate` decimal(20, 2) NULL DEFAULT NULL COMMENT '存量率（hyfl_07粮食收购）',
  `number_of_l_c` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '信用证号数（hyfl_09出口服务)_fp',
  `the_verification_no` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '核销单号（hyfl_09出口服务)_fp',
  `contract_number` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '合同号码（hyfl_09出口服务)_fp',
  `exchange_rate` decimal(20, 2) NULL DEFAULT NULL COMMENT '汇率（hyfl_09出口服务)_fp',
  `currency` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '币种（hyfl_09出口服务)_fp',
  `nature_of_the_water` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '用水性质（hyfl_08/35水电业)',
  `door_no` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '户号（hyfl_08/35水电业)',
  `table_a_no` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '表位号（hyfl_08/35水电业)',
  `in_several_of_the_previous_period` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '上期示数（hyfl_08/35水电业)',
  `the_current_readings` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '本期示数（hyfl_08/35水电业)',
  `practical_water` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '实用水量',
  `meter_reading_date` timestamp(6) NULL DEFAULT NULL COMMENT '抄表日期（hyfl_08/35水电业)',
  `c_a_l` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '口径（hyfl_08/35水电业)',
  `payment_methods` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '缴费方式（hyfl_08/35水电业)',
  `water_meter_state` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '水表状态（hyfl_08/35水电业)',
  `fpxl_fb` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '1.门诊2.住院（tyyl）',
  `registration_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '姓名（tyyl,slmz,slzy）',
  `patient_number` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '病例号（tyyl）',
  `health_care_type` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '医保类型（tyyl,slmz）',
  `type_of_medical_institution` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '医疗机构类型（tyyl）',
  `social_security_number` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '社会保障号码（tyyl,slmz,slzy）',
  `cash_account` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '现金支付（tyyl,slmz）',
  `i_account_abstract` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '个人账户本年支付（tyyl,slzy）',
  `i_account_this_year_pay` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '个人账户本年余额（tyyl,slzy）',
  `i_account_this_year_balance` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '个人账户历年支付（tyyl,slzy）',
  `i_account_over_the_year_pay` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '个人账户历年余额（tyyl,slzy）',
  `i_account_over_the_year_balance` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '医保账户（tyyl,slmz,slzy）',
  `settlement_date` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '结算日期（slmz,slzy）',
  `western_medicine_fee` decimal(20, 2) NULL DEFAULT NULL COMMENT '西药费（slmz,slzy）',
  `t_c_m_fee` decimal(20, 2) NULL DEFAULT NULL COMMENT '中药费（slmz,slzy）',
  `proprietary_chinese_medicine` decimal(20, 2) NULL DEFAULT NULL COMMENT '中成药（slmz,slzy）',
  `registration_fee` decimal(20, 2) NULL DEFAULT NULL COMMENT '挂号费（slmz）',
  `inspecting_fee` decimal(20, 2) NULL DEFAULT NULL COMMENT '诊查费（slmz,slzy）',
  `inspection_fee` decimal(20, 2) NULL DEFAULT NULL COMMENT '检查费（slmz,slzy）',
  `by122_je` decimal(20, 2) NULL DEFAULT NULL COMMENT '票面检查费下方预留空白处对应字段（票面8行2列）（slmz）',
  `by124_mc` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '票面检查费下方预留空白处对应字段（票面9行1列）（tyyl,slmz）',
  `by124_je` decimal(20, 2) NULL DEFAULT NULL COMMENT '票面检查费下方预留空白处对应字段（票面9行2列）（slmz）',
  `diagnostic_test_fee` decimal(20, 2) NULL DEFAULT NULL COMMENT '化验费（slmz）',
  `survey_fee` decimal(20, 2) NULL DEFAULT NULL COMMENT '检验费（slzy）',
  `treatment_fee` decimal(20, 2) NULL DEFAULT NULL COMMENT '治疗费（slmz，slzy）',
  `by120_je` decimal(20, 2) NULL DEFAULT NULL COMMENT '票面检查费下方预留空白处对应字段（票面4行4列）(slmz,slzy)',
  `operation_fee` decimal(20, 2) NULL DEFAULT NULL COMMENT '手术费（slmz，slzy）',
  `blood_transfusion_fee` decimal(20, 2) NULL DEFAULT NULL COMMENT '输血费（slmz，slzy）',
  `oxygen_fee` decimal(20, 2) NULL DEFAULT NULL COMMENT '输氧费（slmz）',
  `materials_expenses_fee` decimal(20, 2) NULL DEFAULT NULL COMMENT '材料费（slmz，slzy）',
  `medical_information_other` decimal(20, 2) NULL DEFAULT NULL COMMENT '其他（slmz，slzy）',
  `western_medicine_fee_isc` decimal(20, 2) NULL DEFAULT NULL COMMENT '西药费_其中自理（slzy）',
  `proprietary_chinese_medicine_isc` decimal(20, 2) NULL DEFAULT NULL COMMENT '中成药_其中自理（slzy）',
  `t_c_m_fee_isc` decimal(20, 2) NULL DEFAULT NULL COMMENT '中草药_其中自理（slzy）',
  `daily_room_fee_isc` decimal(20, 2) NULL DEFAULT NULL COMMENT '床位费_其中自理（slzy）',
  `inspecting_fee_isc` decimal(20, 2) NULL DEFAULT NULL COMMENT '诊查费_其中自理（slzy）',
  `inspection_fee_isc` decimal(20, 2) NULL DEFAULT NULL COMMENT '检查费_其中自理（slzy）',
  `by101_zl` decimal(20, 2) NULL DEFAULT NULL COMMENT '票面检查费自理下方预留空白处对应地段（票面10行3列）（slzy）',
  `by104_zl` decimal(20, 2) NULL DEFAULT NULL COMMENT '票面检查费自理下方预留空白处对应地段（票面11行3列）（slzy）',
  `survey_fee_isc` decimal(20, 2) NULL DEFAULT NULL COMMENT '检验费_自理（slzy）',
  `treatment_fee_isc` decimal(20, 2) NULL DEFAULT NULL COMMENT '治疗费_自理（slzy）',
  `by107_zl` decimal(20, 2) NULL DEFAULT NULL COMMENT '票面检查费自理下方预留空白处对应地段（票面14行3列）（slzy）',
  `operation_fee_isc` decimal(20, 2) NULL DEFAULT NULL COMMENT '手术费_自理（slzy）',
  `blood_transfusion_fee_isc` decimal(20, 2) NULL DEFAULT NULL COMMENT '输血费_自理（slzy）',
  `nursing_fee_isc` decimal(20, 2) NULL DEFAULT NULL COMMENT '护理费_自理（slzy）',
  `materials_expenses_fee_isc` decimal(20, 2) NULL DEFAULT NULL COMMENT '材料费_自理（slzy）',
  `other_fee_isc` decimal(20, 2) NULL DEFAULT NULL COMMENT '其他_自理（slzy）',
  `by110_zl` decimal(20, 2) NULL DEFAULT NULL COMMENT '票面检查其他自理下方预留空白处对应字段（票面20行3列）（slzy）',
  `by113_zl` decimal(20, 2) NULL DEFAULT NULL COMMENT '票面检查其他自理下方预留空白处对应字段（票面21行3列）（slzy）',
  `m_insurance_settlement_information` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '医保结算信息（slmz）',
  `personnel_category` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '人员类别（slzy）',
  `admission_number` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '住院号(slzy)',
  `work_units` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '工作单位(slzy)',
  `admission_date` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '住院日期(slzy)',
  `daily_room_fee` decimal(20, 2) NULL DEFAULT NULL COMMENT '床位费(slzy)',
  `by101_mc` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '输氧费(slzy)',
  `by101_je` decimal(20, 2) NULL DEFAULT NULL COMMENT '输氧费(slzy)',
  `by104_mc` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '票面治疗费下方预留空白处对应地段（票面11行1列）（slzy）',
  `by104_je` decimal(20, 2) NULL DEFAULT NULL COMMENT '票面治疗费下方预留空白处对应地段（票面11行2列）（slzy）',
  `by107_mc` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '票面治疗费下方预留空白处对应地段（票面14行1列）（slzy）',
  `by107_je` decimal(20, 2) NULL DEFAULT NULL COMMENT '票面治疗费下方预留空白处对应地段（票面14行2列）（slzy）',
  `nursing_fee` decimal(20, 2) NULL DEFAULT NULL COMMENT '护理费（slzy）',
  `by110_je` decimal(20, 2) NULL DEFAULT NULL COMMENT '票面治疗费下方预留空白处对应地段（票面21行2列）（slzy）',
  `by113_je` decimal(20, 2) NULL DEFAULT NULL COMMENT '票面治疗费下方预留空白处对应地段（票面22行2列）（slzy）',
  `cash` decimal(20, 2) NULL DEFAULT NULL COMMENT '现金（slzy）',
  `current_year_account` decimal(20, 2) NULL DEFAULT NULL COMMENT '本年账户（slzy）',
  `over_the_years_account` decimal(20, 2) NULL DEFAULT NULL COMMENT '历年账户（slzy）',
  `health_care_account` decimal(20, 2) NULL DEFAULT NULL COMMENT '医保账户（slzy）',
  `by116_je` decimal(20, 2) NULL DEFAULT NULL COMMENT '票面医保账户下方预留空白处对应字段（票面9行4列）（slzy）',
  `by118_je` decimal(20, 2) NULL DEFAULT NULL COMMENT '票面医保账户下方预留空白处对应字段（票面10行4列）（slzy）',
  `payment_in_advance` decimal(20, 2) NULL DEFAULT NULL COMMENT '预缴款（slzy）',
  `payment_of_money` decimal(20, 2) NULL DEFAULT NULL COMMENT '补缴（slzy）',
  `payment_of_cash` decimal(20, 2) NULL DEFAULT NULL COMMENT '补缴：其中现金（slzy）',
  `payment_of_cheque` decimal(20, 2) NULL DEFAULT NULL COMMENT '补缴：其中支票（slzy）',
  `refund` decimal(20, 2) NULL DEFAULT NULL COMMENT '退款（slzy）',
  `including_cash` decimal(20, 2) NULL DEFAULT NULL COMMENT '其中：现金（slzy）',
  `refund_cheque` decimal(20, 2) NULL DEFAULT NULL COMMENT '退款支票（slzy）',
  `total_charge_items` decimal(20, 2) NULL DEFAULT NULL COMMENT '收费项目_合计（slzy）',
  `among_total_charge_items` decimal(20, 2) NULL DEFAULT NULL COMMENT '其中自理自费合计（slzy）',
  `total_end_information` decimal(20, 2) NULL DEFAULT NULL COMMENT '结算信息_合计（slzy）',
  `billing_date` timestamp(6) NULL DEFAULT NULL COMMENT '开票日期',
  PRIMARY KEY (`fpdjh`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '附表信息' ROW_FORMAT = DYNAMIC;

SET FOREIGN_KEY_CHECKS = 1;
